app:
  show_version_update: true
  version_check_url: https://raw.githubusercontent.com/sansan0/TrendRadar/refs/heads/master/version
crawler:
  default_proxy: http://127.0.0.1:10086
  enable_crawler: true
  request_interval: 1000
  use_proxy: false
notification:
  bark_batch_size: 4000
  batch_send_interval: 3
  dingtalk_batch_size: 20000
  enable_notification: true
  feishu_batch_size: 30000
  feishu_message_separator: ━━━━━━━━━━━━━━━━━━━
  max_accounts_per_channel: 3
  message_batch_size: 4000
  push_window:
    enabled: false
    once_per_day: true
    push_record_retention_days: 7
    time_range:
      end: '22:00'
      start: '20:00'
  slack_batch_size: 4000
  webhooks:
    bark_url: ''
    dingtalk_url: ''
    email_from: ''
    email_password: ''
    email_smtp_port: ''
    email_smtp_server: ''
    email_to: ''
    feishu_url: ''
    ntfy_server_url: https://ntfy.sh
    ntfy_token: ''
    ntfy_topic: ''
    slack_webhook_url: ''
    telegram_bot_token: ''
    telegram_chat_id: ''
    wework_msg_type: markdown
    wework_url: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=93c6ed1c-200f-46f2-8617-677b9f4beaaf
platforms:
- id: toutiao
  name: 今日头条
- id: baidu
  name: 百度热搜
- id: thepaper
  name: 澎湃新闻
- id: ifeng
  name: 凤凰网
- id: cankaoxiaoxi
  name: 参考消息
- id: sputniknewscn
  name: 卫星通讯社
- id: zaobao
  name: 联合早报
- id: mktnews
  name: MKT新闻
- id: kaopu
  name: 靠谱新闻
- id: wallstreetcn-hot
  name: 华尔街见闻 最热
- id: wallstreetcn-quick
  name: 华尔街见闻 快讯
- id: wallstreetcn-news
  name: 华尔街见闻 最新
- id: cls-hot
  name: 财联社热门
- id: gelonghui
  name: 格隆汇
- id: xueqiu
  name: 雪球
- id: jin10
  name: 金十数据
- id: fastbull
  name: 快讯通
- id: weibo
  name: 微博
- id: douyin
  name: 抖音
- id: bilibili-hot-search
  name: bilibili 热搜
- id: tieba
  name: 贴吧
- id: zhihu
  name: 知乎
- id: hupu
  name: 虎扑
- id: ithome
  name: IT之家
- id: juejin
  name: 掘金
- id: github
  name: GitHub
- id: hackernews
  name: Hacker News
- id: solidot
  name: Solidot
- id: v2ex
  name: V2EX
- id: nowcoder
  name: 牛客网
- id: pcbeta
  name: 远景论坛
- id: sspai
  name: 少数派
- id: producthunt
  name: ProductHunt
- id: chongbuluo
  name: 虫部落
- id: tencent-hot
  name: 腾讯新闻 综合早报
- id: cls-telegraph
  name: 财联社 电报
- id: cls-depth
  name: 财联社 深度
- id: fastbull-express
  name: 法布财经 快讯
- id: fastbull-news
  name: 法布财经 头条
report:
  max_news_per_keyword: 0
  mode: incremental
  rank_threshold: 5
  reverse_content_order: false
  sort_by_position_first: false
weight:
  frequency_weight: 0.3
  hotness_weight: 0.1
  rank_weight: 0.6
